""" 
This file contains examples of co-simulations of FMUs generated by pyfmu.
These scenarios are simulated using fmpy's master algorithm
"""



def test_sumOfConstants(self):

    
    """We test:
    2 x ConstantSignalSource
    1 x Adder
    """

    pass