# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Build and update wrappers

on:
  push:
    branches: "fix-ci"
  pull_request:
    branches: "fix-ci"

jobs:
  build-wrapper-windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install package
        run: |
          pip install -e.[dev]

      - name: Build wrapper and export examples
        run: |
          python build.py -ue

      - name: Rust tests
        run: | 
          python build.py --rust-tests

      - name: python tests
        run: | 
          python build.py --python-tests

      - name: Upload wrapper
        uses: actions/upload-artifact@v1
        with:
          name: windows-wrapper
          path: src/pyfmu/resources/wrapper/binaries/win64/pyfmu.dll

  build-wrapper-linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # pyo3 requires development headers on ubuntu
      - uses: deadsnakes/action@v1.0.0
        with:
          python-version: 3.8-dev
      - run: python --version --version && which python

      - name: Set up Python 3.8
        run: |
          sudo apt install python3.8-dev

      - name: Install package
        run: |
          pip install -e.[dev]

      # some dependencies are missing for Ubuntu
      # see "known issues" in readme.md 
      - name: Missing dependencies
        run: |
          sudo apt-get install --reinstall libxcb-xinerama0

      - name: Build wrapper and export examples
        run: |
          python build.py -ue

      - name: Rust tests
        run: | 
          python build.py --rust-tests

      - name: python tests
        run: | 
          python build.py --python-tests

      - name: Upload wrapper
        uses: actions/upload-artifact@v1
        with:
          name: windows-wrapper
          path: src/pyfmu/resources/wrapper/binaries/linux64/pyfmu.so

  update-wrappers:
    needs: [build-wrapper-windows, build-wrapper-linux]

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: download windows wrapper
        uses: actions/download-artifact@v1
        with:
          name: windows-wrapper
          path: src/pyfmu/resources/wrapper/binaries/win64/

      - name: download linux wrappers
        uses: actions/download-artifact@v1
        with:
          name: linux-wrapper
          path: src/pyfmu/resources/wrapper/binaries/linux64/

      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Updated wrappers for Linux and Windows" -a --allow-empty
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: ${{github.ref}}
          github_token: ${{ secrets.GITHUB_TOKEN }}
