# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Build and update wrappers

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-wrapper-windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - name: install conan
        run: |
          pip install conan

      - name: Build using CMAKE
        run: |
          python build.py -u

      - name: setup and test
        run: |
          pip install .
          pytest

      - name: Upload wrapper
        uses: actions/upload-artifact@v1
        with:
          name: windows-wrapper
          path: build/pyfmu.dll

  build-wrapper-linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - name: install conan
        run: |
          pip install conan

      - name: check compiler versions
        run: |
          cmake --version
          g++ --version
          g++-9 --version

      - name: Build using CMAKE
        run: |
          export CXX=g++-9
          export C=gcc-9
          python build.py -u

      - name: setup and test
        run: |
          pip install .
          pytest

      - name: Upload wrapper
        uses: actions/upload-artifact@v1
        with:
          name: linux-wrapper
          path: build/pyfmu.so

  update-wrappers:
    needs: [build-wrapper-windows, build-wrapper-linux]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: download windows wrapper
        uses: actions/download-artifact@v1
        with:
          name: windows-wrapper
          path: src/pyfmu/resources/wrapper/binaries/win64/

      - name: download linux wrappers
        uses: actions/download-artifact@v1
        with:
          name: linux-wrapper
          path: src/pyfmu/resources/wrapper/binaries/linux64/

      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Updated wrappers for Linux and Windows" -a
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
